apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: hellolora/local_k8s_fastapi:0.0.1 # name of the docker image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  selector:
    app: fastapi-app
  type: NodePort # expose the service on a port of the node
  ports: 
  - port: 8000 # service port (cluster-internal)
    targetPort: 80
    nodePort: 30000 # the port of the node where the service is accessible